### PR TITLE
GUAC-298: Add configuration option to allow for VNC clipboard text en…

### PR DESCRIPTION
**Pull request by flangelo**
…coding override

### CODE REVIEW

**Comment by mike-jumper** [comment]
What VNC servers allow this?

From what I've tested before, VNC servers fail unpredictably if clipboard data is not in ISO 8859-1, as mandated by the VNC standard.

**Comment by flangelo** [comment]
The ESXi VNC server supports UTF-8, this is what we're using.

**Comment by mike-jumper** [comment]
Ah, OK.

**Comment by mike-jumper** [comment]
Merging via #59.

##### Important point #####

The original clipboard encoding parsing function would silently default to ISO8859-1 if the provided encoding name was invalid. If we're warning that a connection has been explicitly configured to use a non-standard encoding, we should probably also warn if the explicitly-chosen encoding is not going to be used after all.

I have made this change myself via 5e4c7de.

##### Nitpick points #####

1. Each structure member needs its own comment. Can't use a single comment to cover multiple members.
2. We have recently changed the style used for JavaDoc and Doxygen comments. `@param` and other similar tags should be separated from each other by blank lines, with their content indented on the following line(s) by four spaces. For example: https://github.com/glyptodon/guacamole-server/blob/615921108a0c9a02eacee31c4b487a00c814af11/src/libguac/guacamole/protocol.h#L251-L270

**Pull request closed without merging**
