### PR TITLE
GUAC-1366: Adjust WebP and JPEG image sizes before compressing to avo…

### PR DESCRIPTION
**Pull request by flangelo**
…id artifacts on the edges of the images

### CODE REVIEW

**Comment by dynamiccast** [comment]
Does this solve the problem for you ? I still experience the same artifacts.

**Comment by flangelo** [comment]
The artifacts are not completely eliminated. When using WebP there are still some artifacts. For JPEG they are mostly gone.

**Comment by mike-jumper** [comment]
@flangelo, can you quantify the improvement somehow? Perhaps a screenshot or two?

**Comment by flangelo** [comment]
WebP before:
webp_before
WebP after
webp_after
JPEG before:
jpeg_before
JPEG after:
jpeg_after

**Comment by mike-jumper** [comment]
Thanks, @flangelo. Very clear improvements.

**Pull request merged**
